### ISSUE TITLE
要望　TAB文字を押したとき、指定した文字数だけ空白を半角で挿入する機能

### ISSUE THREAD

**Issue by korarei** [sigma-axis/aviutl_reactive_dlg#1]
タイトルにあるとおり、TAB文字を押したとき、指定した文字数だけ空白を半角で挿入する機能を要望します。例えば、設定ファイルで4と指定していれば、TABキーを押したときに空白が4文字追加されるという感じです。
TAB文字の幅を変更する機能が現在存在するため、この機能と本要望内容を設定ファイルで切り替えることができるようにしていただければ幸いです。

**Comment by sigma-axis** [comment]
ある程度の制約はあるものの可能であったため実装してみました．

1. キーボードからの直接の `TAB` 入力でないと機能しません．例えばクリップボードから貼り付けたり，`Ctrl+TAB` を入力した場合にはそのまま TAB 文字が入力されます．

   実装上の理由としてはウィンドウメッセージ `WM_CHAR` を置き換えることで実現していますが，クリップボードからの貼り付けなどはそのメッセージを介さないため置き換えが起こりません．

   また，クリップボードの貼り付けなどは標準コントロールの機能であるため介入が難しく，仮にできたとしても不整合やバグの種になりやすいため，手を入れないのが無難と判断したのも理由です．

2. 既存の TAB 文字幅を指定する機能とは共存・独立して動作する機能となります．

   先述の通りこの機能があっても TAB 文字と空白文字の共存は避けられないため，TAB 文字を Edit コントロールが取り扱う設定も有意義になるためです．

次のバージョン更新で利用可能になる予定ですが，よければ動作確認をしていただければと思います．[こちら](https://github.com/sigma-axis/aviutl_reactive_dlg/actions/runs/8142077659)の Artifacts からバイナリをダウンロードできます (GitHub へのログインが必要). 要望通りの機能かどうかを含めてご意見お聞かせいただければ幸いです．

**Comment by sigma-axis** [comment]
追記:
- Artifacts の保持期間は90日までです．
- `[TextBox.Tweaks]` 以下の `tab_to_spaces_text` と `tab_to_spaces_script` で空白文字の個数を指定できます．同梱 `.ini` ファイルのコメントにも仕様の記述があるのでそちらもご参照ください．

**Comment by korarei** [comment]
要望の機能が動作することを確認しました。意見を受け入れていただきありがとうございました。

**Comment by sigma-axis** [comment]
v1.20 でこの機能を追加しました．少し拡張して任意のテキストを代わりに挿入する形にしました．複数個の半角空白も可能ですし，全角空白や `<p+80,+0>` のような制御文字の挿入もできるようになりました．

以前試していただいたものとは設定ファイルの互換性がなくなりましたが，その点はテスト版だったということでご容赦ください．

追記: 有意義なご提案ありがとうございました．
