### ISSUE TITLE
v1.20 Microsoft Defenderでウイルス扱いされる

### ISSUE THREAD

**Issue by korarei** [sigma-axis/aviutl_reactive_dlg#2]
DLした際Microsoft Defenderによってはじかれます。
![スクリーンショット (468)](https://github.com/sigma-axis/aviutl_reactive_dlg/assets/132204522/45a2a33c-7bf0-40cd-ab49-0c28e7495bd6)
![スクリーンショット (469)](https://github.com/sigma-axis/aviutl_reactive_dlg/assets/132204522/7fb3d3ef-6dde-428e-bc76-eaade0307625)

**Comment by sigma-axis** [comment]
確認しました．

私の自環境でのビルドでは大丈夫でしたが，GitHubの自動ビルドによるバイナリだと誤検出されるようでした．

バイナリの機能自体は自環境でのビルドと同じはずなので問題はないと考えています．現状私の側で対処できる方法はないため，Windows Defender の除外対象に指定するか，自環境でビルドしていただければと思います．
